### ISSUE TITLE
Error after updating to HA 2025.7.4

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#496]
After updating to HA 2025.7.4 the integration would not load anymore. When looking into the logfile I noticed the following error:

-----

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 11:26:55 (4 occurrences)
Last logged: 11:42:35

Error setting up entry Bosch EasyControl CT200 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 151, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 249, in async_init
    if await self.async_init_bosch():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 302, in async_init_bosch
    await self.gateway.check_connection()
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/gateway/base.py", line 336, in check_connection
    await self.initialize()
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/gateway/base.py", line 77, in initialize
    await self._update_info(initial_db.get(GATEWAY))
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/gateway/easycontrol.py", line 81, in _update_info
    response = await self._connector.get(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 131, in get
    data = await self._request(method=GET, path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 153, in _request
    self.client.connect()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/connectors/client/slixmpp010.py", line 16, in connect
    return super().connect(enable_plaintext=True)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClientXMPP.connect() got an unexpected keyword argument 'enable_plaintext'

----

Hope this helps.

**Comment by JHurk** [comment]
Seems like a generic issue, mine is broken as well after upgrading to 7.4

**Comment by fate8383** [comment]
discussing also since yesterday in discord, but it is an issue so lets follow up here.

**Comment by dasphilipt** [comment]
Same here ... the integration doesn't work anymore since 7.4..
Does anyone know if we can expect a solution soon? Thank you!

**Comment by Kimvdp1988** [comment]
Same to me 😒 hope for fix soon

**Comment by przemoc86** [comment]
For me also :(

**Comment by Salvora** [comment]
editing the slixmpp010.py as described by @fgrfn works as a temporary workaround.

**Comment by fate8383** [comment]
I believe this is on core HA, integration needs to have something to overwrite this. Which is not a simple code edit in the integration. I might be wrong. But this change definitely made it work.

**Comment by ellinoise** [comment]
i have same problem with HA v.2025.7.4(

**Comment by fgrfn** [comment]
> Thanks, [@fgrfn](https://github.com/fgrfn), I've implemented your changes, and it fixed the issue.
> Do you plan to push in master?

> I believe this is on core HA, integration needs to have something to overwrite this. Which is not a simple code edit in the integration. I might be wrong. But this change definitely made it work.

Unfortunately, I'm not very familiar with developing HA integrations, but that's my observation as well.
I think @pszafer needs to take a look at it to find a final solution

**Comment by crumets** [comment]
> > Same for me, can't find the slixmpp010.py in Homeassistant OS.
> 
> Are you on .28.0? It's not there on .26

Home Assistant OS 16.0

**Comment by TimWohl** [comment]
Same here at 7.4 🙋🏼‍♂️

**Comment by jfhautenauven** [comment]
Same issue here after latest HA update

**Comment by vincenzomartusciello** [comment]
use my repo while this repo is not update
https://github.com/vincenzomartusciello/ha-bosch/releases/tag/v0.28.1
it's only a temp solution please check daily this repo

**Comment by rjdgroot** [comment]
Same here. Stopped working since 29-07 6am CEST. 
Dit update my HA from 2025.7.1 to 2025.7.4 but that was yesterday (30-07) around 6pm so that shouldn’t be the issue.

**Comment by TimWohl** [comment]
> use my repo while this repo is not update https://github.com/vincenzomartusciello/ha-bosch/releases/tag/v0.28.1 it's only a temp solution please check daily this repo


Using version 0.28.1 of Vinveco. I just tested it. 
Works, thanks a lot.

**Comment by pszafer** [comment]
Fixed in v0.28.2
