### ISSUE TITLE
CT100 - Error connecting Bosch at 559931372 - ClientXMPP.connect() got an unexpected keyword argument 'enable_plaintext'

### ISSUE THREAD

**Issue by Tomiliy** [bosch-thermostat/home-assistant-bosch-custom-component#499]
**Describe the bug**
The configuration was still working. After the last Update from Homeasistant now: 

The Integration stop working and would'nt reload or restart. I deleted the entry and try to add them again.
an error appers in the Logfile:
Logger: custom_components.bosch.config_flow
Quelle: custom_components/bosch/config_flow.py:175
Integration: Bosch thermostat (Dokumentation, Probleme)
Erstmals aufgetreten: 23:29:52 (3 Vorkommnisse)
Zuletzt protokolliert: 23:31:27

Error connecting Bosch at 559931372 - ClientXMPP.connect() got an unexpected keyword argument 'enable_plaintext'

**To Reproduce**
Delete the Entry and add them again. 
After Serial, Access and Password the error appears

**Expected behavior**
Nothing

**Screenshots**
<img width="624" height="791" alt="Image" src="https://github.com/user-attachments/assets/eeb54b3b-9b9f-4c65-b7e0-8fe9849ce446" />

**Version**
  - Home Assistant OS: Core 2025.7.4  2025.07.2
    Operating System: 16.0
   Frontend:  20250702.3
  - HA Bosch component version?: 0.28.0
  - Python Bosch HTTP client version? 

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**

**Comment by whiteduck22** [comment]
I have a similar issue with CT200. I thought it was my setup as following a wifi change I had to reset the CT200. I did earlier have some success before an upgrade to HA but all devices were disabled. I have tried resetting the password in the Bosch app. By the way @Tomiliy not sure you intended to share your device serial and auth token in the picture. Thanks 

ClientXMPP.connect() got an unexpected keyword argument 'enable_plaintext'

HA versions as per @Tomiliy

**Comment by whiteduck22** [comment]
Updated to 28.2 and things appear to be working... will monitor

**Comment by whiteduck22** [comment]
Strange - many sensors are disabled - I am manually able to enable them...

**Comment by ManiakNL** [comment]
> Updated to 28.2 and things appear to be working... will monitor

Same here, thank dev for the quick fix :)

**Comment by whiteduck22** [comment]
After manually enabling the sensors, things look to be working well with v28.2 and my CT200. Thank you dev!
