### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by cyberoeze** [bosch-thermostat/home-assistant-bosch-custom-component#458]
After Updating the OS to 14.1 on a raspberry pi 4

the Integration will not Load anymore

Logger: homeassistant.util.package
Quelle: util/package.py:78
Erstmals aufgetreten: 17:34:22 (1 Vorkommnisse)
Zuletzt protokolliert: 17:34:22

Installed version for bosch-thermostat-client resolved to None

and then i think as a result.

Logger: homeassistant.config_entries
Quelle: config_entries.py:3314
Erstmals aufgetreten: 17:34:31 (1 Vorkommnisse)
Zuletzt protokolliert: 17:34:31

Error occurred loading flow for integration bosch: cannot import name 'DHW' from 'bosch_thermostat_client.const' (/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/const/__init__.py)
