### ISSUE TITLE
Integration error after update to 0.18.0.dev2: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by M4v3r1cK87** [bosch-thermostat/home-assistant-bosch-custom-component#161]
**Describe the bug**
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 18:12:19 (1 occurrences)
Last logged: 18:12:19

Setup failed for custom integration bosch: Unable to import component: cannot import name 'DeviceClassEntity' from 'bosch_thermostat_client.helper' (/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/helper.py)

**To Reproduce**
Restart HomeAssistant after the HACS Bosch package update

**Expected behavior**
Home Assistant restart correctly

**Screenshots**

**Version**
  - HA version? Home Assistant Core 2022.6.4
  - HA Bosch component version? 0.18.0.dev
  - Python Bosch HTTP client version?

** Debug SCAN **
N/A

**Additional context**
N/A

**Comment by M4v3r1cK87** [comment]
After update the version to 0.18.0.dev2 I obtain this:

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.loader
Source: custom_components/bosch/__init__.py:11
Integration: Bosch thermostat (documentation, issues)
First occurred: 18:35:10 (1 occurrences)
Last logged: 18:35:10

Unexpected exception importing component custom_components.bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 11, in <module>
    from bosch_thermostat_client.const import (
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
    from .gateway import gateway_chooser
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
    from .ivt import IVTGateway
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/ivt.py", line 22, in <module>
    from .base import BaseGateway
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 6, in <module>
    from bosch_thermostat_client.circuits import Circuits
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/__init__.py", line 1, in <module>
    from .circuits import Circuits
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/circuits.py", line 12, in <module>
    from .circuit import BasicCircuit
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/circuit.py", line 28, in <module>
    from bosch_thermostat_client.sensors import Sensors
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/sensors/__init__.py", line 6, in <module>
    from .sensors import Sensors
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/sensors/sensors.py", line 21, in <module>
    from bosch_thermostat_client.sensors.ecus_recording import EcusRecordingSensor
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/sensors/ecus_recording.py", line 15, in <module>
    class EcusRecordingSensor(Sensor):
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/sensors/ecus_recording.py", line 81, in EcusRecordingSensor
    def page_number(self) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by pszafer** [comment]
can you check now? I tested it on python3.10 only, forgot to apply some patches for python3.9

**Comment by Didel** [comment]
Can confirm it is fixed by v0.18.0.dev3 !

**Comment by M4v3r1cK87** [comment]
Hi Pszafer, OK is fixed by 0.18.0.dev3
Thank you so much
